// DIFESMAQ mock data
export const ZAHORY_SAC_DATA = {
  fx: 3.745,
  projects: ["Todos", "Pepas de Oro", "Buenaventura", "Antapaccay", "Uchucchacua"],

  // Módulo 1 — Clientes
  clientes: [
    { id: 'C001', razonSocial: 'Buenaventura S.A.A.',      ruc: '20100122398', contacto: 'Ing. Ramírez Torres',  email: 'contratos@buenaventura.com.pe', telefono: '(01) 419-2500', estado: 'Activo' },
    { id: 'C002', razonSocial: 'Minsur S.A.',              ruc: '20100113514', contacto: 'Ing. Quispe Mamani',   email: 'mant@minsur.com.pe',           telefono: '(01) 215-3000', estado: 'Activo' },
    { id: 'C003', razonSocial: 'Antapaccay - Glencore',   ruc: '20521141789', contacto: 'Luis Anderson R.',     email: 'l.anderson@antapaccay.com',    telefono: '+51 984 112 334', estado: 'Activo' },
    { id: 'C004', razonSocial: 'Volcan Cía. Minera S.A.A.',ruc: '20100077660', contacto: 'Arq. Condori V.',      email: 'contratos@volcan.com.pe',      telefono: '(01) 219-7000', estado: 'Activo' },
    { id: 'C005', razonSocial: 'Gold Fields La Cima',     ruc: '20504741551', contacto: 'Ing. Flores Huanca',   email: 'mant@goldfields.com.pe',       telefono: '+51 976 443 210', estado: 'Inactivo' },
  ],

  // Módulo 1 — Contratos / OS
  contratos: [
    {
      id: 'CT001', numero: 'CT-2025-BUE-001', clienteId: 'C001', cliente: 'Buenaventura S.A.A.',
      tipo: 'Contrato', descripcion: 'Servicio de mantenimiento JB-24 y SC-701 — Unidad Uchucchacua',
      moneda: 'USD', fechaInicio: '2025-01-01', fechaFin: '2025-12-31',
      estado: 'Activo', condicionFact: 'Por período mensual',
      equiposScope: ['JB-24', 'SC-701'], dmp: 97.92,
      obs: 'Renovación automática si ninguna parte notifica con 60 días de anticipación.'
    },
    {
      id: 'CT002', numero: 'OS-2026-APC-011', clienteId: 'C003', cliente: 'Antapaccay - Glencore',
      tipo: 'OS', descripcion: 'Orden de servicio mantenimiento JB-26 — Espinar',
      moneda: 'USD', fechaInicio: '2026-01-15', fechaFin: '2026-07-15',
      estado: 'Activo', condicionFact: 'Por OT aprobada',
      equiposScope: ['JB-26'], dmp: 98.00,
      obs: 'Incluye penalidad de 5% sobre factura si DMR < DMP por más de 3 guardias consecutivas.'
    },
    {
      id: 'CT003', numero: 'CT-2026-PEP-003', clienteId: 'C002', cliente: 'Minsur S.A.',
      tipo: 'Contrato', descripcion: 'Mantenimiento JB-DD311 — Pepas de Oro',
      moneda: 'USD', fechaInicio: '2026-02-01', fechaFin: '2026-12-31',
      estado: 'Activo', condicionFact: 'Por período mensual',
      equiposScope: ['JB-DD311'], dmp: 97.92,
      obs: ''
    },
    {
      id: 'CT004', numero: 'OS-2025-VOL-008', clienteId: 'C004', cliente: 'Volcan Cía. Minera S.A.A.',
      tipo: 'OS', descripcion: 'Reparación mayor scoop — Cerro de Pasco',
      moneda: 'USD', fechaInicio: '2025-11-01', fechaFin: '2026-03-31',
      estado: 'Cerrado', condicionFact: 'Por hito',
      equiposScope: ['EQ-TALLER-01'], dmp: 97.92,
      obs: 'Cerrado con conformidad del cliente 31/03/2026.'
    },
  ],

  // Panel E — Estado actual de activos
  activosEstado: [
    { cod: 'JB-DD311', marca: 'SANDVIK DD311-40', tipo: 'Jumbo', proyecto: 'Pepas de Oro',  propietario: 'DIFESMAQ', ubicacion: 'Mina',            estadoOp: 'Operativo',     ultimaOT: 'OT-2026-047', proximoMantto: 'PM en 85 hrs',    dmr: 97.44, dmp: 97.92 },
    { cod: 'JB-24',    marca: 'EPIROC SIMBA S7D', tipo: 'Simba', proyecto: 'Buenaventura',  propietario: 'DIFESMAQ', ubicacion: 'Mina',            estadoOp: 'Operativo',     ultimaOT: 'OT-2026-050', proximoMantto: 'PM en 120 hrs',   dmr: 98.10, dmp: 97.92 },
    { cod: 'JB-26',    marca: 'EPIROC SIMBA S7D', tipo: 'Simba', proyecto: 'Antapaccay',    propietario: 'DIFESMAQ', ubicacion: 'Mina',            estadoOp: 'Operativo',     ultimaOT: 'OT-2026-048', proximoMantto: 'PM en 210 hrs',   dmr: 97.95, dmp: 98.00 },
    { cod: 'SC-701',   marca: 'SANDVIK',          tipo: 'Scoop', proyecto: 'Buenaventura',  propietario: 'Cliente',  ubicacion: 'Mina',            estadoOp: 'En mantenimiento', ultimaOT: 'OT-2026-049', proximoMantto: '—',               dmr: 96.50, dmp: 97.92 },
    { cod: 'EQ-TALL-01', marca: 'CATERPILLAR R1600', tipo: 'Scoop', proyecto: 'Uchucchacua', propietario: 'Cliente', ubicacion: 'Taller Carapongo', estadoOp: 'En taller',     ultimaOT: 'OT-2026-051', proximoMantto: '—',               dmr: null,  dmp: null },
    { cod: 'JB-NEW-01',  marca: 'EPIROC BOOMER S2', tipo: 'Jumbo', proyecto: '—',            propietario: 'DIFESMAQ', ubicacion: 'Taller Carapongo', estadoOp: 'Acondicionamiento', ultimaOT: 'OT-2026-054', proximoMantto: 'Listo en ~15 días', dmr: null, dmp: null },
  ],
  equipos: [
    { cod: "JB-DD311", marca: "SANDVIK DD311-40", proyecto: "Pepas de Oro", ctx: "Mina" },
    { cod: "JB-24", marca: "EPIROC SIMBA S7D", proyecto: "Buenaventura", ctx: "Mina" },
    { cod: "JB-26", marca: "EPIROC SIMBA S7D", proyecto: "Buenaventura", ctx: "Mina" },
    { cod: "SC-701", marca: "SANDVIK", proyecto: "Buenaventura", ctx: "Mina" },
    { cod: "EQ-TALLER-01", marca: "CATERPILLAR R1600", proyecto: "Uchucchacua", ctx: "Taller Carapongo" },
  ],
  tecnicos: [
    { nombre: "Pajuelo Jurado, Edson", rol: "Mecatrónico", ctx: "Mina", proy: "Buenaventura", tarifa: 18.50 },
    { nombre: "Miranda Barra, Sandro", rol: "Mecánico", ctx: "Mina", proy: "Pepas de Oro", tarifa: 15.00 },
    { nombre: "García Quispe, Roberto", rol: "Mecánico", ctx: "Mina", proy: "Buenaventura", tarifa: 15.00 },
    { nombre: "Torres Mamani, Miguel", rol: "Electricista", ctx: "Mina", proy: "Antapaccay", tarifa: 16.00 },
    { nombre: "López Vargas, Carlos", rol: "Mecánico", ctx: "Taller Carapongo", proy: "—", tarifa: 14.00 },
  ],
  standardJobs: [
    { id: 'SJ-001', codigo: 'SJ-HYD-001', descripcion: 'Cambio kit de sellos cilindro hidraulico', sistemaId: 'HID', horasEstimadasMo: 6, operacionesDefault: ['Bloquear energia y despresurizar circuito', 'Desmontar cilindro', 'Cambiar sellos y armar', 'Prueba de presion y fugas'], repuestosDefault: [{ codigo: 'REP-9900-SEL', cantidad: 1 }, { codigo: 'INS-0088-AH5', cantidad: 2 }] },
    { id: 'SJ-002', codigo: 'SJ-ENG-002', descripcion: 'Diagnostico baja potencia motor diesel', sistemaId: 'MOT', horasEstimadasMo: 4, operacionesDefault: ['Descargar codigos ECM', 'Inspeccionar admision y filtros', 'Medir parametros de combustible', 'Emitir reporte de diagnostico'], repuestosDefault: [{ codigo: 'REP-2201-AIR', cantidad: 2 }, { codigo: 'INS-0055-MOT', cantidad: 1 }] },
    { id: 'SJ-003', codigo: 'SJ-PER-003', descripcion: 'Inspeccion y ajuste sistema de percusion', sistemaId: 'PER', horasEstimadasMo: 5, operacionesDefault: ['Inspeccionar culata y acumuladores', 'Medir presion de percusion', 'Ajustar parametros', 'Prueba operacional con registro ECM'], repuestosDefault: [{ codigo: 'REP-3310-PER', cantidad: 1 }] },
  ],
  otSegmentos: [
    { id: 'SEG-050-01', otId: 'OT-2026-050', numeroSegmento: '01', descripcion: 'Reparacion sistema hidraulico', tipoCargo: 'Cliente_Contrato', standardJobId: 'SJ-001' },
    { id: 'SEG-049-01', otId: 'OT-2026-049', numeroSegmento: '01', descripcion: 'Diagnostico motor diesel', tipoCargo: 'Cliente_Contrato', standardJobId: 'SJ-002' },
  ],
  otOperaciones: [
    { id: 'OP-050-01', segmentoId: 'SEG-050-01', numeroOperacion: '01', descripcion: 'Desmontar cilindro hidraulico' },
    { id: 'OP-050-02', segmentoId: 'SEG-050-01', numeroOperacion: '02', descripcion: 'Cambiar kit de sellos y probar' },
    { id: 'OP-049-01', segmentoId: 'SEG-049-01', numeroOperacion: '01', descripcion: 'Descargar codigos ECM' },
  ],
  confiabilidad: [
    { eq: 'SC-701', horasOperacion: 420, otsCorrectivas: 7, paradasCorrectivas: 41, horasHombreMtto: 96 },
    { eq: 'JB-DD311', horasOperacion: 510, otsCorrectivas: 5, paradasCorrectivas: 28, horasHombreMtto: 72 },
    { eq: 'JB-26', horasOperacion: 585, otsCorrectivas: 4, paradasCorrectivas: 18, horasHombreMtto: 61 },
    { eq: 'JB-24', horasOperacion: 610, otsCorrectivas: 3, paradasCorrectivas: 12, horasHombreMtto: 44 },
    { eq: 'EQ-TALL-01', horasOperacion: 190, otsCorrectivas: 3, paradasCorrectivas: 22, horasHombreMtto: 58 },
  ],
  dmrByEquipo: [
    { eq: "JB-DD311", proy: "Pepas de Oro", dmr: 97.44, dmp: 97.92, hrep: 2.33, estado: "riesgo" },
    { eq: "JB-24",    proy: "Buenaventura", dmr: 98.10, dmp: 97.92, hrep: 0.00, estado: "cumpliendo" },
    { eq: "SC-701",   proy: "Buenaventura", dmr: 96.50, dmp: 97.92, hrep: 4.50, estado: "incumpliendo" },
    { eq: "JB-26",    proy: "Antapaccay",   dmr: 97.95, dmp: 97.92, hrep: 0.50, estado: "cumpliendo" },
  ],
  otsDashboard: [
    { codigo: 'OT-2026-050', eq: 'JB-24',    tec: 'Pajuelo E.', fecha: '16/04', costo: 772,   margen: 92.4, estado: 'Aprobada',  tipoTrabajo: 'Correctivo',        tipoCargo: 'Cliente_Contrato', lineaNegocio: 'flota_alquileres' },
    { codigo: 'OT-2026-049', eq: 'SC-701',   tec: 'García R.',  fecha: '15/04', costo: 1764,  margen: 74.1, estado: 'Pendiente', tipoTrabajo: 'Preventivo_PM',     tipoCargo: 'Cliente_Contrato', lineaNegocio: 'flota_alquileres' },
    { codigo: 'OT-2026-048', eq: 'JB-26',    tec: 'Torres M.',  fecha: '14/04', costo: 565,   margen: 93.4, estado: 'Aprobada',  tipoTrabajo: 'Correctivo',        tipoCargo: 'Cliente_Contrato', lineaNegocio: 'flota_alquileres' },
    { codigo: 'OT-2026-047', eq: 'JB-DD311', tec: 'Miranda B.', fecha: '13/04', costo: 2100,  margen: 85.2, estado: 'Cerrada',   tipoTrabajo: 'Correctivo',        tipoCargo: 'Cliente_Contrato', lineaNegocio: 'flota_alquileres' },
    { codigo: 'OT-2026-046', eq: 'JB-NEW-01',tec: 'López V.',   fecha: '12/04', costo: 3200,  margen: null, estado: 'En taller', tipoTrabajo: 'Acondicionamiento', tipoCargo: 'Interno_Zahory',   lineaNegocio: 'interno_zahory'   },
    { codigo: 'OT-2026-045', eq: 'SC-701',   tec: 'García R.',  fecha: '10/04', costo: 980,   margen: null, estado: 'Aprobada',  tipoTrabajo: 'Correctivo',        tipoCargo: 'Reclamo_Rework',   lineaNegocio: 'flota_alquileres' },
    { codigo: 'OT-2026-044', eq: 'JB-24',    tec: 'Pajuelo E.', fecha: '08/04', costo: 450,   margen: 88.0, estado: 'Aprobada',  tipoTrabajo: 'Preventivo_PM',     tipoCargo: 'Cliente_Contrato', lineaNegocio: 'flota_alquileres' },
  ],  // Full OT cost breakdown — incluye costoEstimado para gráfico de desviación (v4.0)
  // facturable: true = activo del cliente; false = acondicionamiento activo propio
  otsCostos: [
    { codigo: 'OT-2026-050', eq: 'JB-24',    proy: 'Buenaventura', fecha: '16/04', tipoTrabajo: 'Correctivo',       tec: 'Pajuelo E.',  mo: 222,  mat: 490,  tra: 60,  ingreso: 10200, tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-15', fechaAprobacionComercial: '2026-04-15T09:00:00', fechaPrimerLaborReal: '2026-04-15T18:20:00', motivoRetrabajo: '', moEst: 200, matEst: 420, traEst: 50 },
    { codigo: 'OT-2026-048', eq: 'JB-26',    proy: 'Antapaccay',   fecha: '14/04', tipoTrabajo: 'Correctivo',       tec: 'Torres M.',   mo: 185,  mat: 320,  tra: 60,  ingreso: 8500,  tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-14', fechaAprobacionComercial: '2026-04-13T11:00:00', fechaPrimerLaborReal: '2026-04-14T08:00:00', motivoRetrabajo: '', moEst: 180, matEst: 300, traEst: 60 },
    { codigo: 'OT-2026-052', eq: 'JB-DD311', proy: 'Pepas de Oro', fecha: '12/04', tipoTrabajo: 'Preventivo_PM',    tec: 'Miranda B.',  mo: 350,  mat: 1600, tra: 150, ingreso: 9350,  tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-12', fechaAprobacionComercial: '2026-04-11T08:00:00', fechaPrimerLaborReal: '2026-04-12T08:30:00', motivoRetrabajo: '', moEst: 300, matEst: 1400,traEst: 120 },
    { codigo: 'OT-2026-049', eq: 'SC-701',   proy: 'Buenaventura', fecha: '15/04', tipoTrabajo: 'Preventivo_PM',    tec: 'García R.',   mo: 444,  mat: 1200, tra: 120, ingreso: 6800,  tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-15', fechaAprobacionComercial: '2026-04-14T10:00:00', fechaPrimerLaborReal: '2026-04-15T07:30:00', motivoRetrabajo: '', moEst: 400, matEst: 1100,traEst: 100 },
    { codigo: 'OT-2026-051', eq: 'JB-24',    proy: 'Buenaventura', fecha: '10/04', tipoTrabajo: 'Correctivo',       tec: 'Pajuelo E.',  mo: 280,  mat: 620,  tra: 80,  ingreso: 5100,  tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-10', fechaAprobacionComercial: '2026-04-09T09:30:00', fechaPrimerLaborReal: '2026-04-10T09:00:00', motivoRetrabajo: '', moEst: 250, matEst: 580, traEst: 80 },
    { codigo: 'OT-2026-047', eq: 'JB-DD311', proy: 'Pepas de Oro', fecha: '13/04', tipoTrabajo: 'Correctivo',       tec: 'Miranda B.',  mo: 310,  mat: 850,  tra: 90,  ingreso: 12750, tipoCargo: 'Cliente_Contrato', fechaProgramadaInicio: '2026-04-13', fechaAprobacionComercial: '2026-04-12T16:00:00', fechaPrimerLaborReal: '2026-04-13T10:00:00', motivoRetrabajo: '', moEst: 280, matEst: 900, traEst: 90 },
    { codigo: 'OT-2026-046', eq: 'SC-701',   proy: 'Buenaventura', fecha: '12/04', tipoTrabajo: 'Correctivo',       tec: 'García R.',   mo: 800,  mat: 2100, tra: 300, ingreso: 0,     tipoCargo: 'Reclamo_Rework', fechaProgramadaInicio: '2026-04-12', fechaAprobacionComercial: '2026-04-10T15:00:00', fechaPrimerLaborReal: '2026-04-12T09:30:00', motivoRetrabajo: 'Repeticion de falla por ajuste incompleto en taller', moEst: 600, matEst: 1800,traEst: 200 },
    { codigo: 'OT-2026-053', eq: 'JB-26',    proy: 'Antapaccay',   fecha: '08/04', tipoTrabajo: 'Correctivo',       tec: 'Torres M.',   mo: 900,  mat: 1900, tra: 180, ingreso: 0,     tipoCargo: 'Garantia_Fabrica', fechaProgramadaInicio: '2026-04-08', fechaAprobacionComercial: '2026-04-07T09:00:00', fechaPrimerLaborReal: '2026-04-08T12:00:00', motivoRetrabajo: '', moEst: 750, matEst: 1600,traEst: 150 },
    { codigo: 'OT-2026-054', eq: 'JB-NEW-01',proy: '—',            fecha: '20/04', tipoTrabajo: 'Acondicionamiento', tec: 'López V.',   mo: 1200, mat: 8500, tra: 400, ingreso: 0,     tipoCargo: 'Interno_Zahory', fechaProgramadaInicio: '2026-04-20', fechaAprobacionComercial: null, fechaPrimerLaborReal: null, motivoRetrabajo: '', moEst: 1000,matEst: 8000,traEst: 350 },
  ],  solicitudesUrgentes: [
    { tipo: "URGENTE", desc: "Kit de drives",   cant: 1, tec: "Miranda B.", proy: "Pepas de Oro", fecha: "16/04", estado: "Pendiente" },
    { tipo: "URGENTE", desc: "Lock tite",        cant: 1, tec: "Miranda B.", proy: "Pepas de Oro", fecha: "16/04", estado: "Pendiente" },
    { tipo: "URGENTE", desc: "Palanca L 3/4",   cant: 1, tec: "Miranda B.", proy: "Pepas de Oro", fecha: "16/04", estado: "Pendiente" },
    { tipo: "NORMAL",  desc: "Filtro hidráulico",cant: 2, tec: "Pajuelo E.", proy: "Buenaventura", fecha: "15/04", estado: "En proceso" },
    { tipo: "NORMAL",  desc: "Aceite 15W-40",    cant: "5 GAL", tec: "Torres M.", proy: "Antapaccay", fecha: "14/04", estado: "Atendido" },
  ],
  historialMina: [
    { fecha: "16/04", turno: "DÍA",   eq: "JB-DD311", proy: "Pepas de Oro", tec: "Miranda B.", ht: 2.9, dm: 97.9, costo: 480, estado: "Aprobado" },
    { fecha: "15/04", turno: "NOCHE", eq: "JB-24",    proy: "Buenaventura", tec: "Pajuelo E.", ht: 3.9, dm: 97.9, costo: 620, estado: "Aprobado" },
    { fecha: "15/04", turno: "DÍA",   eq: "SC-701",   proy: "Buenaventura", tec: "García R.",  ht: 0,   dm: 97.9, costo: 0,   estado: "Pendiente" },
    { fecha: "14/04", turno: "NOCHE", eq: "JB-26",    proy: "Antapaccay",   tec: "Torres M.",  ht: 3.1, dm: 98.5, costo: 390, estado: "Aprobado" },
    { fecha: "14/04", turno: "DÍA",   eq: "JB-DD311", proy: "Pepas de Oro", tec: "Miranda B.", ht: 2.0, dm: 97.9, costo: 290, estado: "Rechazado" },
  ],
  repuestos: [
    { cod: "REP-4412-HYD", np: "57789123", desc: "Filtro hidráulico EPIROC SIMBA", cat: "Hidráulico",  um: "Unidad", usd: 320, ctx: "Mina",   activo: true,  stock: 2,  min: 3  },
    { cod: "REP-2201-AIR", np: "44512890", desc: "Filtro de aire",                   cat: "Filtros",    um: "Unidad", usd: 85,  ctx: "Ambos",  activo: true,  stock: 8,  min: 5  },
    { cod: "INS-0088-AH5", np: "—",         desc: "Aceite hidráulico ISO 46 5L",     cat: "Lubricantes",um: "Litro",  usd: 58,  ctx: "Ambos",  activo: true,  stock: 15, min: 10 },
    { cod: "INS-0012-GR",  np: "—",         desc: "Grasa multiuso (tubo)",           cat: "Consumibles",um: "Unidad", usd: 12,  ctx: "Ambos",  activo: true,  stock: 4,  min: 8  },
    { cod: "REP-7701-ELC", np: "99012345",  desc: "Conector eléctrico 440V",         cat: "Eléctrico",  um: "Unidad", usd: 45,  ctx: "Taller", activo: true,  stock: 0,  min: 2  },
    { cod: "REP-9900-SEL", np: "HYD-SK-88", desc: "Kit de sellos hidráulicos",       cat: "Hidráulico",  um: "Kit",    usd: 180, ctx: "Ambos",  activo: true,  stock: 1,  min: 2  },
    { cod: "INS-0055-MOT", np: "—",          desc: "Aceite de motor 15W-40 (galón)",  cat: "Lubricantes",um: "Galón",  usd: 32,  ctx: "Ambos",  activo: true,  stock: 20, min: 10 },
    { cod: "REP-3310-PER", np: "SD-311-P1", desc: "Culata de percusión SANDVIK",     cat: "Percusión",  um: "Unidad", usd: 1450,ctx: "Mina",   activo: true,  stock: 0,  min: 1  },
  ],
  personalOperativo: [
    { cod: "TEC-001", nombre: "Pajuelo Jurado, Edson",   cargo: "Técnico Mecatrónico", esp: "Mecatrónico", proy: "Buenaventura", ctx: "Mina",    costoHora: 18.50, costoExtra: 27.75, sctr: "2026-12-31", licencia: "2026-09-15", emo: "2026-06-30", induccion: "2027-01-10", habilitado: true,  estado: "Activo" },
    { cod: "TEC-002", nombre: "Miranda Barra, Sandro",   cargo: "Técnico Mecánico",    esp: "Mecánico",    proy: "Pepas de Oro",  ctx: "Mina",    costoHora: 15.00, costoExtra: 22.50, sctr: "2026-08-20", licencia: "2025-11-30", emo: "2026-04-15", induccion: "2026-07-22", habilitado: false, estado: "Activo" },
    { cod: "TEC-003", nombre: "García Quispe, Roberto",  cargo: "Técnico Mecánico",    esp: "Mecánico",    proy: "Buenaventura", ctx: "Mina",    costoHora: 15.00, costoExtra: 22.50, sctr: "2026-11-01", licencia: "2026-11-01", emo: "2026-11-01", induccion: "2026-11-01", habilitado: true,  estado: "Activo" },
    { cod: "TEC-004", nombre: "Torres Mamani, Miguel",   cargo: "Técnico Electricista",esp: "Electricista", proy: "Antapaccay",   ctx: "Mina",    costoHora: 16.00, costoExtra: 24.00, sctr: "2026-10-15", licencia: "2026-10-15", emo: "2026-10-15", induccion: "2026-10-15", habilitado: true,  estado: "Activo" },
    { cod: "TEC-005", nombre: "López Vargas, Carlos",    cargo: "Técnico Mecánico",    esp: "Mecánico",    proy: "—",            ctx: "Carapongo",costoHora: 14.00, costoExtra: 21.00, sctr: "2026-05-01", licencia: "2027-03-20", emo: "2026-05-01", induccion: "2026-05-01", habilitado: false, estado: "Inactivo" },
  ],
  propuestas: [
    { n: "PROP-2026-001", cliente: "Buenaventura S.A.",   proy: "Renovación JB-24",     fecha: "10/04", usd: 180000, estado: "Aceptada" },
    { n: "PROP-2026-002", cliente: "Volcan Cía. Minera",  proy: "Nuevo SC",             fecha: "15/04", usd: 240000, estado: "Enviada" },
    { n: "PROP-2026-003", cliente: "Antapaccay",          proy: "Ampliación taller",    fecha: "18/04", usd: 95000,  estado: "Borrador" },
  ],
  remisiones: [
    { n: "REM-2026-047", ots: "OT-047, OT-048", periodo: "Abr 2026", cliente: "Buenaventura S.A.", usd: 14280, estado: "Conformada" },
  ],
  consolidadoJB_DD311: [
    { turno: "DÍA",   fecha: "26/03", mIni: 3588.30, mFin: 3588.30, pIni: 2099.70, pFin: 2099.70, eIni: 3908.10, eFin: 3908.10, ht: 0.00, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 11.75, total: 12.00, dm: 97.92, obs: "Equipo no ingresa a labor por falta de sostenimiento." },
    { turno: "NOCHE", fecha: "26/03", mIni: 3588.30, mFin: 3589.20, pIni: 2099.70, pFin: 2101.40, eIni: 3908.10, eFin: 3908.40, ht: 1.20, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 10.55, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "DÍA",   fecha: "27/03", mIni: 3589.20, mFin: 3590.60, pIni: 2101.40, pFin: 2103.30, eIni: 3908.40, eFin: 3911.30, ht: 4.30, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 7.45, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "NOCHE", fecha: "27/03", mIni: 3590.60, mFin: 3592.40, pIni: 2103.30, pFin: 2105.80, eIni: 3911.30, eFin: 3915.10, ht: 5.50, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 6.25, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "DÍA",   fecha: "28/03", mIni: 3592.40, mFin: 3594.90, pIni: 2105.80, pFin: 2109.10, eIni: 3915.10, eFin: 3920.20, ht: 7.40, prg: 0.25, prv: 0.00, acc: 0, ctvo: 0, hsb: 4.35, total: 12.00, dm: 97.92, obs: "Operación normal." },
    { turno: "NOCHE", fecha: "28/03", mIni: 3594.90, mFin: 3596.50, pIni: 2109.10, pFin: 2111.50, eIni: 3920.20, eFin: 3924.00, ht: 5.20, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 6.55, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "DÍA",   fecha: "29/03", mIni: 3596.50, mFin: 3598.00, pIni: 2111.50, pFin: 2113.80, eIni: 3924.00, eFin: 3927.10, ht: 4.90, prg: 0.00, prv: 0.25, acc: 0, ctvo: 2.33, hsb: 4.52, total: 12.00, dm: 97.44, obs: "Reparación sistema percusión." },
    { turno: "NOCHE", fecha: "29/03", mIni: 3598.00, mFin: 3599.80, pIni: 2113.80, pFin: 2116.20, eIni: 3927.10, eFin: 3930.90, ht: 6.20, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 5.55, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "DÍA",   fecha: "30/03", mIni: 3599.80, mFin: 3601.90, pIni: 2116.20, pFin: 2118.80, eIni: 3930.90, eFin: 3935.40, ht: 8.70, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 3.05, total: 12.00, dm: 97.92, obs: "—" },
    { turno: "NOCHE", fecha: "30/03", mIni: 3601.90, mFin: 3603.40, pIni: 2118.80, pFin: 2121.00, eIni: 3935.40, eFin: 3939.00, ht: 5.00, prg: 0.00, prv: 0.25, acc: 0, ctvo: 0, hsb: 6.75, total: 12.00, dm: 97.92, obs: "—" },
  ],
  // daily cumulative for month line chart (days 1..30)
  monthDaily: (() => {
    const days = 30;
    let cumCost = 0, cumRev = 0;
    const arr = [];
    const seed = [
      [420, 1100],[680,2400],[0,0],[520,1800],[310,1900],[720,3200],[0,0],[2980,3200],[0,0],[980,5100],
      [0,0],[5300,13200],[1250,12750],[565,8500],[1764,6800],[772,10200],[0,0],[420,2100],[900,4200],[1100,5800],
      [0,0],[560,2400],[820,3100],[0,0],[1320,4800],[0,0],[450,1900],[690,3400],[880,4100],[0,0]
    ];
    for (let i = 0; i < days; i++) {
      cumCost += seed[i][0];
      cumRev += seed[i][1];
      arr.push({ d: i+1, cost: cumCost, rev: cumRev });
    }
    return arr;
  })(),
  contratos_rental: [
    {
      id: 'CTR-001', cliente_id: 'C002', cliente_nombre: 'Minsur S.A.',
      equipos: ['LHD-R1600G-001', 'LHD-R1300G-002'],
      tipo_tarifa: 'disponibilidad',
      tarifa_base: 18500,
      meta_dmp: 85, penalidad_pct: 0.5,
      moneda: 'USD',
      fecha_inicio: '2026-01-01', fecha_fin: '2026-12-31',
      estado: 'activo', unidad_minera: 'La Oroya',
    },
    {
      id: 'CTR-002', cliente_id: 'C004', cliente_nombre: 'Volcan Cía. Minera S.A.A.',
      equipos: ['LHD-R1600H-003'],
      tipo_tarifa: 'por_hora',
      tarifa_hora: 85, horas_minimas: 400,
      moneda: 'USD',
      fecha_inicio: '2026-02-01', fecha_fin: '2026-07-31',
      estado: 'activo', unidad_minera: 'Cerro de Pasco',
    },
  ],
  liquidaciones: [
    {
      id: 'LIQ-2026-04-001', contrato_id: 'CTR-001', equipo_id: 'LHD-R1600G-001',
      periodo: '2026-04', horas_facturables: 612, dmr_real: 82.4, meta_dmp: 85,
      penalidad: 2775, total_usd: 15725, estado: 'en_conciliacion',
      observaciones_conciliacion: [
        { concepto: 'Horas parada programada día 14', valor_zahory: 612, valor_cliente: 598, resuelto: false },
      ],
    },
  ],
  actas: [
    {
      id: 'ACTA-001', tipo: 'despacho',
      contrato_id: 'CTR-001', equipo_id: 'LHD-R1600G-001',
      fecha: '2026-01-03', horometro: 14250,
      estado_equipo: 'operativo', operador_recibe: 'Juan Quispe',
      observaciones: 'Sin observaciones',
    },
  ],
  ordenes_fabricacion: [
    {
      id: 'OF-2026-001',
      codigo: 'OF-2026-001',
      cliente_id: 'CLI-003',
      cliente_nombre: 'AESA Infraestructura y Minería',
      os_id: 'OS-MAE-001',
      descripcion: 'Fabricación de cangilón reforzado para LHD R1600H',
      tipo_origen: 'especificaciones_cliente',
      materiales_del_cliente: false,
      estado: 'en_ejecucion',
      fecha_apertura: '2026-05-02',
      fecha_compromiso: '2026-05-20',
      jefe_taller: 'Roberto Quispe',
      supervisor_qc: 'Miguel Huanca',
      precio_os: 12400,
      anticipo: 3720,
      moneda: 'USD',
      tipo_qc: 'QC-EST',
      componente: null,
      bom_planificado: [
        { codigo: 'MAT-001', descripcion: 'Plancha AR400 1/2"', cantidad: 4, unidad: 'und', costo_unit: 380, es_material_cliente: false },
        { codigo: 'MAT-002', descripcion: 'Electrodo supercito 1/8"', cantidad: 12, unidad: 'kg', costo_unit: 18, es_material_cliente: false },
      ],
      bom_real: [
        { codigo: 'MAT-001', descripcion: 'Plancha AR400 1/2"', cantidad: 4, unidad: 'und', costo_unit: 380, es_material_cliente: false },
        { codigo: 'MAT-002', descripcion: 'Electrodo supercito 1/8"', cantidad: 14, unidad: 'kg', costo_unit: 18, es_material_cliente: false, motivo_desviacion: 'Mayor área de refuerzo requerida en esquinas' },
        { codigo: 'MAT-003', descripcion: 'Disco de desbaste 7"', cantidad: 6, unidad: 'und', costo_unit: 8, es_material_cliente: false, motivo_desviacion: 'No estaba en BOM inicial — requerido en acabado' },
      ],
      operaciones: [
        { id: 'OP-001', descripcion: 'Trazado y corte', tecnico: 'Luis Mamani', horas_est: 8, horas_real: 9, estado: 'aprobada', aprobado_por: 'Roberto Quispe', tiempo_estandar_id: 'TE-001', horas_estandar: 8 },
        { id: 'OP-002', descripcion: 'Armado y soldadura', tecnico: 'Luis Mamani', horas_est: 16, horas_real: 14, estado: 'en_progreso', aprobado_por: null, tiempo_estandar_id: 'TE-003', horas_estandar: 6 },
        { id: 'OP-003', descripcion: 'Acabado y pintura', tecnico: 'Pedro Ccoa', horas_est: 6, horas_real: 0, estado: 'pendiente', aprobado_por: null, tiempo_estandar_id: 'TE-006', horas_estandar: 8 },
      ],
      historial_qc: [],
      tipo_entrega: null,
      ot_instalacion_id: null,
      otas_vinculadas: [],
      garantia: null,
    },
    {
      id: 'OF-2026-002',
      codigo: 'OF-2026-002',
      cliente_id: 'CLI-001',
      cliente_nombre: 'Doe Run Perú',
      os_id: 'OS-MAE-002',
      descripcion: 'Reparación de cilindro de dirección LHD R1300G',
      tipo_origen: 'ingenieria_zahory',
      materiales_del_cliente: false,
      estado: 'en_qc',
      fecha_apertura: '2026-04-28',
      fecha_compromiso: '2026-05-12',
      jefe_taller: 'Roberto Quispe',
      supervisor_qc: 'Miguel Huanca',
      precio_os: 4800,
      anticipo: 0,
      moneda: 'USD',
      tipo_qc: 'QC-HID',
      componente: {
        numero_serie: 'CIL-DIR-R1300G-001',
        descripcion_componente: 'Cilindro de dirección lado derecho',
        modelo_equipo_compatible: 'LHD R1300G / R1600G',
        es_componente_nuevo: false,
        ingresado_por_cliente: true,
      },
      bom_planificado: [
        { codigo: 'MAT-010', descripcion: 'Sello hidráulico kit completo', cantidad: 1, unidad: 'kit', costo_unit: 320, es_material_cliente: false },
        { codigo: 'MAT-011', descripcion: 'Cromo duro (servicio tercero)', cantidad: 1, unidad: 'serv', costo_unit: 650, es_material_cliente: false },
      ],
      bom_real: [
        { codigo: 'MAT-010', descripcion: 'Sello hidráulico kit completo', cantidad: 1, unidad: 'kit', costo_unit: 320, es_material_cliente: false },
        { codigo: 'MAT-011', descripcion: 'Cromo duro (servicio tercero)', cantidad: 1, unidad: 'serv', costo_unit: 650, es_material_cliente: false },
      ],
      operaciones: [
        { id: 'OP-001', descripcion: 'Desmontaje y diagnóstico', tecnico: 'Pedro Ccoa', horas_est: 4, horas_real: 4, estado: 'aprobada', aprobado_por: 'Roberto Quispe', tiempo_estandar_id: 'TE-004', horas_estandar: 4 },
        { id: 'OP-002', descripcion: 'Rectificado y cromado', tecnico: 'Servicio tercero', horas_est: 0, horas_real: 0, estado: 'aprobada', aprobado_por: 'Roberto Quispe', tiempo_estandar_id: null, horas_estandar: null },
        { id: 'OP-003', descripcion: 'Ensamble y prueba hidráulica', tecnico: 'Pedro Ccoa', horas_est: 6, horas_real: 5, estado: 'aprobada', aprobado_por: 'Roberto Quispe', tiempo_estandar_id: 'TE-005', horas_estandar: 6 },
      ],
      historial_qc: [
        {
          fecha: '2026-05-11',
          supervisor: 'Miguel Huanca',
          resultado: 'observada',
          motivo: 'Fuga leve detectada en prueba de presión a 250 bar',
          items_observados: ['Ensamble de sello superior'],
        },
      ],
      tipo_entrega: 'entrega_fisica',
      ot_instalacion_id: null,
      otas_vinculadas: [],
      garantia: null,
    },
  ],

  propuestas_ingenieria: [
    {
      id: 'ING-2026-001',
      cliente_id: 'CLI-004',
      cliente_nombre: "Corporación Makario's SAC",
      descripcion_problema: 'Brazo de boom con fisuras en zona de soldadura',
      diagnostico: 'Fatiga por ciclos repetitivos. Requiere refuerzo estructural y cambio de geometría en unión.',
      plano_generado: true,
      bom_preliminar: [
        { descripcion: 'Plancha A36 3/8"', cantidad: 2, unidad: 'und' },
        { descripcion: 'Soldadura bajo hidrógeno', cantidad: 5, unidad: 'kg' },
      ],
      responsable_ingenieria: 'Roberto Quispe',
      fecha: '2026-05-08',
      estado: 'aprobada_por_cliente',
      of_generada_id: null,
    },
  ],

  tiempos_estandar: [
    { id: 'TE-001', operacion: 'Trazado y corte plancha hasta 1"',        horas: 8,  unidad: 'por pieza' },
    { id: 'TE-002', operacion: 'Soldadura estructural (por metro lineal)', horas: 2,  unidad: 'por metro' },
    { id: 'TE-003', operacion: 'Armado y punteo de estructura',            horas: 6,  unidad: 'por pieza' },
    { id: 'TE-004', operacion: 'Desmontaje y diagnóstico hidráulico',      horas: 4,  unidad: 'por cilindro' },
    { id: 'TE-005', operacion: 'Ensamble y prueba hidráulica',             horas: 6,  unidad: 'por cilindro' },
    { id: 'TE-006', operacion: 'Acabado y pintura (granallado + epóxico)', horas: 8,  unidad: 'por pieza' },
    { id: 'TE-007', operacion: 'Mecanizado en torno (desbaste)',           horas: 3,  unidad: 'por hora máquina' },
    { id: 'TE-008', operacion: 'Mecanizado en torno (acabado)',            horas: 2,  unidad: 'por hora máquina' },
    { id: 'TE-009', operacion: 'Inspección dimensional',                   horas: 1,  unidad: 'por pieza' },
    { id: 'TE-010', operacion: 'Prueba de presión hidráulica',             horas: 2,  unidad: 'por circuito' },
  ],

  criterios_qc: [
    {
      id: 'QC-HID',
      tipo_trabajo: 'Reparación hidráulica',
      criterios: [
        { id: 'C001', descripcion: 'Prueba de presión estática',     valor_minimo: 280, unidad: 'bar',        duracion_min: 30,   metodo: 'Manómetro calibrado' },
        { id: 'C002', descripcion: 'Prueba de presión dinámica',     valor_minimo: 250, unidad: 'bar',        duracion_min: 10,   metodo: 'Banco hidráulico' },
        { id: 'C003', descripcion: 'Verificación de fugas visuales', valor_minimo: 0,   unidad: 'gotas/min',  duracion_min: 15,   metodo: 'Inspección visual' },
        { id: 'C004', descripcion: 'Carrera de vástago',             valor_minimo: null, unidad: 'mm',        duracion_min: null, metodo: 'Según plano del fabricante' },
      ],
    },
    {
      id: 'QC-EST',
      tipo_trabajo: 'Fabricación estructural',
      criterios: [
        { id: 'C010', descripcion: 'Inspección visual de cordones de soldadura', valor_minimo: null, unidad: null,  duracion_min: null, metodo: 'AWS D1.1' },
        { id: 'C011', descripcion: 'Verificación dimensional general',           valor_minimo: null, unidad: 'mm',  duracion_min: null, metodo: 'Cinta métrica / pie de rey' },
        { id: 'C012', descripcion: 'Prueba de impacto (si aplica)',              valor_minimo: null, unidad: 'J',   duracion_min: null, metodo: 'Charpy según norma' },
        { id: 'C013', descripcion: 'Verificación de pintura (espesor)',          valor_minimo: 250,  unidad: 'µm',  duracion_min: null, metodo: 'Medidor de espesor magnético' },
      ],
    },
    {
      id: 'QC-MEC',
      tipo_trabajo: 'Mecanizado',
      criterios: [
        { id: 'C020', descripcion: 'Diámetro exterior',     valor_minimo: null, unidad: 'mm',  duracion_min: null, metodo: 'Micrómetro — tolerancia según plano' },
        { id: 'C021', descripcion: 'Rugosidad superficial', valor_minimo: null, unidad: 'Ra',  duracion_min: null, metodo: 'Rugosímetro o comparador visual' },
        { id: 'C022', descripcion: 'Dureza superficial',    valor_minimo: 58,   unidad: 'HRC', duracion_min: null, metodo: 'Durómetro Rockwell' },
      ],
    },
  ],

  pasaportes_componentes: [
    {
      numero_serie: 'CIL-DIR-R1300G-001',
      descripcion: 'Cilindro de dirección lado derecho',
      modelo_compatible: 'LHD R1300G / R1600G',
      cliente_propietario: 'Doe Run Perú',
      historial: [
        {
          of_id: 'OF-2025-014',
          fecha: '2025-08-10',
          tipo: 'Reparación',
          trabajo: 'Cambio de sellos hidráulicos y rectificado de vástago',
          tecnico: 'Pedro Ccoa',
          qc_aprobado_por: 'Miguel Huanca',
          materiales_usados: ['Sello hidráulico kit', 'Cromo duro (servicio)'],
        },
      ],
    },
  ],

  reclamos_garantia: [
    {
      id: 'REC-2026-001',
      of_origen_id: 'OF-2025-014',
      cliente_id: 'CLI-001',
      cliente_nombre: 'Doe Run Perú',
      numero_serie: 'CIL-DIR-R1300G-001',
      fecha_reclamo: '2026-03-10',
      descripcion_falla: 'Fuga de aceite por sello superior a los 45 días de operación',
      estado: 'of_garantia_generada',
      of_garantia_id: 'OF-2026-003',
      procede_garantia: true,
      motivo_rechazo: null,
    },
  ],

  backlog: [
    { bkl: 'BKL-2026-090', fecha: '20/04/2026', eq: 'SC-701',   sistema: 'Motor',        hallazgo: 'SOS Feedback critico: presencia de limalla y silicio elevado en aceite motor', prioridad: 'Emergencia', score: 17, dias: 0, estado: 'Listo para OT', cicloVida: 'Listo para OT', requiereRetorno: true, fuente: 'SOS Feedback (Analisis de fluidos)', nivelAlertaSos: 'Critico', reporteLaboratorio: 'sos-sc701-2026-04.pdf' },
    { bkl: 'BKL-2026-089', fecha: '20/04/2026', eq: 'JB-DD311', sistema: 'Hidráulico',   hallazgo: 'Fuga de aceite en manguera de percusión de brazo derecho',     prioridad: 'Emergencia',  score: 95, dias: 0, estado: 'Pendiente',        cicloVida: 'Nuevo',              requiereRetorno: true,  fuente: 'Reporte diario' },
    { bkl: 'BKL-2026-088', fecha: '19/04/2026', eq: 'SC-701',   sistema: 'Motor',        hallazgo: 'Pérdida de potencia al subir rampa, humo negro excesivo',       prioridad: 'Urgente',     score: 82, dias: 1, estado: 'Pend. Recursos',   cicloVida: 'Pendiente recursos', requiereRetorno: true,  fuente: 'Reporte diario' },
    { bkl: 'BKL-2026-085', fecha: '18/04/2026', eq: 'JB-24',    sistema: 'Eléctrico',    hallazgo: 'Faro pirata delantero izquierdo quemado',                       prioridad: 'Normal',      score: 45, dias: 2, estado: 'Pendiente',        cicloVida: 'En análisis',        requiereRetorno: false, fuente: 'Reporte diario' },
    { bkl: 'BKL-2026-082', fecha: '15/04/2026', eq: 'JB-26',    sistema: 'Estructura',   hallazgo: 'Desgaste en pines de articulación central',                    prioridad: 'Planificable', score: 30, dias: 5, estado: 'Pendiente',        cicloVida: 'Nuevo',              requiereRetorno: false, fuente: 'Inspección' },
    { bkl: 'BKL-2026-079', fecha: '12/04/2026', eq: 'JB-DD311', sistema: 'Transmisión',  hallazgo: 'Ruido anómalo al cambiar a 2da marcha',                        prioridad: 'Urgente',     score: 75, dias: 8, estado: 'Listo para OT',    cicloVida: 'Listo para OT',      requiereRetorno: false, fuente: 'Parte taller' },
    { bkl: 'BKL-2026-076', fecha: '10/04/2026', eq: 'SC-701',   sistema: 'Hidráulico',   hallazgo: 'Manguera de dirección con micro-fisuras visibles',              prioridad: 'Urgente',     score: 68, dias: 13, estado: 'En análisis',     cicloVida: 'En análisis',        requiereRetorno: true,  fuente: 'Inspección' },
    { bkl: 'BKL-2026-073', fecha: '08/04/2026', eq: 'JB-26',    sistema: 'Eléctrico',    hallazgo: 'Tablero de control presenta falla intermitente en display',    prioridad: 'Normal',      score: 40, dias: 15, estado: 'Pendiente',       cicloVida: 'Nuevo',              requiereRetorno: false, fuente: 'Reporte diario' },
  ],

  // ── Módulo Transporte Comercial ───────────────────────────────────────────
  unidades_transporte: [
    {
      id: 'UNI-001', placa: 'ABC-123', tipo: 'camioneta_4x4',
      marca: 'Toyota', modelo: 'Hilux', año: 2022,
      origen: 'propia', conductor_default: 'Juan Pérez',
      estado: 'disponible', km_actual: 48320, capacidad_carga_kg: 1000,
    },
    {
      id: 'UNI-002', placa: 'XYZ-456', tipo: 'camion_plano',
      marca: 'Volvo', modelo: 'FH', año: 2020,
      origen: 'propia', conductor_default: 'Carlos Ramos',
      estado: 'en_ruta', km_actual: 128400, capacidad_carga_kg: 20000,
    },
    {
      id: 'UNI-003', placa: null, tipo: 'camion_grua',
      marca: 'Proveedor externo', modelo: null, año: null,
      origen: 'tercerizada', proveedor_id: 'PROV-TRANS-001',
      estado: 'disponible', km_actual: null, capacidad_carga_kg: 35000,
    },
  ],

  rutas_maestro: [
    {
      id: 'RUT-001', nombre: 'Lima → La Oroya',
      origen: 'Taller Zahory — Ate, Lima',
      destino: 'Unidad Minera La Oroya — Junín',
      km_estandar: 185, tiempo_estimado_hrs: 4.5,
      tipo_carga_habitual: 'Equipo LHD',
      tarifas: [
        { tipo_unidad: 'camion_plano', tarifa_por_km: 4.5, moneda: 'USD' },
        { tipo_unidad: 'camion_grua',  tarifa_por_km: 6.0, moneda: 'USD' },
      ],
    },
    {
      id: 'RUT-002', nombre: 'Lima → Cerro de Pasco',
      origen: 'Taller Zahory — Ate, Lima',
      destino: 'Unidad Minera Cerro de Pasco',
      km_estandar: 320, tiempo_estimado_hrs: 7,
      tipo_carga_habitual: 'Repuestos y componentes',
      tarifas: [
        { tipo_unidad: 'camioneta_4x4', tarifa_por_km: 2.8, moneda: 'USD' },
        { tipo_unidad: 'camion_plano',  tarifa_por_km: 4.8, moneda: 'USD' },
      ],
    },
  ],

  ordenes_viaje: [
    {
      id: 'OV-2026-001', tipo_operacion: 'propio', estado: 'completada',
      ruta_id: 'RUT-001',
      origen: 'Taller Zahory — Ate, Lima',
      destino: 'Unidad Minera La Oroya — Junín',
      fecha_programada: '2026-05-10',
      carga_descripcion: 'LHD R1600G-001 — traslado post-mantenimiento',
      unidad_id: 'UNI-002', conductor: 'Carlos Ramos', unidad_origen: 'propia',
      vinculo_tipo: 'contrato', vinculo_id: 'CTR-001',
      km_planificado: 185, km_real: 191,
      hora_salida: '06:00', hora_llegada: '10:45',
      combustible_gal: 28, costo_combustible: 140, costo_peajes: 18,
      costo_conductor: 0, costo_tercero: 0, costo_total: 158,
      incidentes: [],
    },
    {
      id: 'OV-2026-002', tipo_operacion: 'comercial', estado: 'en_ruta',
      ruta_id: 'RUT-002',
      origen: 'Taller Zahory — Ate, Lima',
      destino: 'Cerro de Pasco',
      fecha_programada: '2026-05-15',
      carga_descripcion: 'Repuestos para mantenimiento preventivo',
      unidad_id: 'UNI-003', conductor: 'Conductor proveedor', unidad_origen: 'tercerizada',
      proveedor_id: 'PROV-TRANS-001',
      cliente_id: 'CLI-002', contrato_id: 'CTR-TRANS-001',
      tipo_tarifa: 'por_km', tarifa_km: 4.8,
      km_planificado: 320, km_real: null,
      hora_salida: '05:30', hora_llegada: null,
      combustible_gal: null, costo_combustible: 0, costo_peajes: 0,
      costo_conductor: 0, costo_tercero: 1536, costo_total: null,
      ingreso_estimado: 1536,
      incidentes: [],
    },
  ],

  contratos_transporte: [
    {
      id: 'CTR-TRANS-001', cliente_id: 'CLI-002', cliente_nombre: 'Kallpamina',
      tipo_tarifa: 'por_km', tarifa_km: 4.8, moneda: 'USD',
      tipo_unidad_contratada: 'camion_plano',
      fecha_inicio: '2026-03-01', fecha_fin: '2026-08-31',
      estado: 'activo',
    },
  ],

  // ── Módulo Venta de Repuestos ─────────────────────────────────────────────
  listas_precio: [
    {
      id: 'LP-001',
      nombre: 'Clientes contrato alquiler',
      descripcion: 'Descuento del 15% sobre precio base para clientes con contrato de alquiler activo',
      tipo: 'descuento_porcentual',
      descuento_pct: 15,
      clientes_asignados: ['CLI-001', 'CLI-002'],
    },
    {
      id: 'LP-002',
      nombre: 'Precio lista general',
      descripcion: 'Precio base sin descuento. Aplica a clientes sin acuerdo especial.',
      tipo: 'precio_base',
      descuento_pct: 0,
      clientes_asignados: [],
    },
    {
      id: 'LP-003',
      nombre: 'Distribuidor autorizado',
      descripcion: 'Precio especial para distribuidores. Margen reducido sobre costo.',
      tipo: 'margen_sobre_costo',
      margen_pct: 20,
      clientes_asignados: ['CLI-004'],
    },
  ],

  pedidos_venta: [
    {
      id: 'PV-2026-001',
      tipo_cliente: 'contrato',
      cliente_id: 'CLI-001',
      cliente_nombre: 'Doe Run Perú',
      lista_precio_id: 'LP-001',
      estado: 'en_preparacion',
      fecha_pedido: '2026-05-12',
      fecha_entrega_comprometida: '2026-05-16',
      tipo_entrega: 'despacho_a_destino',
      destino: 'Unidad Minera La Oroya',
      items: [
        {
          codigo: 'CAT-8T0814',
          descripcion: 'Filtro hidráulico R1600G',
          modelos_compatibles: ['R1600G', 'R1600H'],
          qty_pedida: 4,
          qty_despachada: 0,
          precio_base: 180,
          descuento_pct: 15,
          precio_final: 153,
          disponibilidad: 'stock',
          stock_reservado: true,
        },
        {
          codigo: 'CAT-1R0741',
          descripcion: 'Filtro de aceite motor R1300G',
          modelos_compatibles: ['R1300G'],
          qty_pedida: 6,
          qty_despachada: 0,
          precio_base: 95,
          descuento_pct: 15,
          precio_final: 80.75,
          disponibilidad: 'a_pedido',
          stock_reservado: false,
          compra_generada_id: 'OC-2026-008',
        },
      ],
      subtotal: 1096.5,
      igv: 197.37,
      total: 1293.87,
      moneda: 'USD',
      notas: 'Entrega urgente — equipo parado en mina',
    },
    {
      id: 'PV-2026-002',
      tipo_cliente: 'interno',
      cliente_id: null,
      cliente_nombre: 'Interno Zahory',
      lista_precio_id: null,
      estado: 'despachado',
      fecha_pedido: '2026-05-10',
      fecha_entrega_comprometida: '2026-05-10',
      tipo_entrega: 'retiro_taller',
      destino: null,
      vinculo_tipo: 'ot',
      vinculo_id: 'OT-2026-048',
      items: [
        {
          codigo: 'CAT-5P0960',
          descripcion: 'Sello de vástago cilindro dirección',
          modelos_compatibles: ['R1300G', 'R1600G'],
          qty_pedida: 2,
          qty_despachada: 2,
          precio_base: 0,
          descuento_pct: 0,
          precio_final: 0,
          disponibilidad: 'stock',
          stock_reservado: false,
        },
      ],
      subtotal: 0,
      igv: 0,
      total: 0,
      moneda: 'USD',
      notas: 'Consumo OT-2026-048',
    },
    {
      id: 'PV-2026-003',
      tipo_cliente: 'esporadico',
      cliente_id: 'CLI-003',
      cliente_nombre: 'Antapaccay - Glencore',
      lista_precio_id: 'LP-002',
      estado: 'confirmado',
      fecha_pedido: '2026-05-14',
      fecha_entrega_comprometida: '2026-05-20',
      tipo_entrega: 'retiro_taller',
      destino: null,
      items: [
        {
          codigo: 'CAT-8T0814',
          descripcion: 'Filtro hidráulico R1600G',
          modelos_compatibles: ['R1600G', 'R1600H'],
          qty_pedida: 2,
          qty_despachada: 0,
          precio_base: 180,
          descuento_pct: 0,
          precio_final: 180,
          disponibilidad: 'stock',
          stock_reservado: true,
        },
      ],
      subtotal: 360,
      igv: 64.8,
      total: 424.8,
      moneda: 'USD',
      notas: '',
    },
  ],

  // Catálogo de repuestos extendido (incluye campos nuevos + entradas CAT-*)
  repuestos_catalogo: [
    {
      codigo: 'REP-4412-HYD', cod: 'REP-4412-HYD',
      descripcion: 'Filtro hidráulico EPIROC SIMBA', desc: 'Filtro hidráulico EPIROC SIMBA',
      marca: 'EPIROC',
      modelos_compatibles: ['R1600G', 'R1300G'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Hidráulico',
      usd: 320, precio_base: 320,
      stock_actual: 2, stock: 2,
      stock_minimo: 3, min: 3,
      stock_reservado: 0,
      costo_aterrizado: 213,
      margen_estandar_pct: 50,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'B-02-04',
      es_importado: true,
      proveedor_habitual: 'PROV-EPI-001',
      plazo_importacion_dias: 45,
      ctx: 'Mina', activo: true,
    },
    {
      codigo: 'REP-2201-AIR', cod: 'REP-2201-AIR',
      descripcion: 'Filtro de aire', desc: 'Filtro de aire',
      marca: 'Donaldson',
      modelos_compatibles: ['R1600G', 'R1600H', 'R1300G'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Filtros',
      usd: 85, precio_base: 85,
      stock_actual: 8, stock: 8,
      stock_minimo: 5, min: 5,
      stock_reservado: 0,
      costo_aterrizado: 56,
      margen_estandar_pct: 52,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'A-01-08',
      es_importado: false,
      proveedor_habitual: 'PROV-DOM-001',
      plazo_importacion_dias: null,
      ctx: 'Ambos', activo: true,
    },
    {
      codigo: 'INS-0012-GR', cod: 'INS-0012-GR',
      descripcion: 'Grasa multiuso (tubo)', desc: 'Grasa multiuso (tubo)',
      marca: 'SKF',
      modelos_compatibles: [],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Consumibles',
      usd: 12, precio_base: 12,
      stock_actual: 4, stock: 4,
      stock_minimo: 8, min: 8,
      stock_reservado: 0,
      costo_aterrizado: 7,
      margen_estandar_pct: 71,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'C-05-01',
      es_importado: false,
      proveedor_habitual: 'PROV-DOM-002',
      plazo_importacion_dias: null,
      ctx: 'Ambos', activo: true,
    },
    {
      codigo: 'REP-9900-SEL', cod: 'REP-9900-SEL',
      descripcion: 'Kit de sellos hidráulicos', desc: 'Kit de sellos hidráulicos',
      marca: 'Parker',
      modelos_compatibles: ['R1600G', 'R1300G'],
      unidad: 'Kit', um: 'Kit',
      cat: 'Hidráulico',
      usd: 180, precio_base: 180,
      stock_actual: 1, stock: 1,
      stock_minimo: 2, min: 2,
      stock_reservado: 0,
      costo_aterrizado: 120,
      margen_estandar_pct: 50,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'B-01-03',
      es_importado: true,
      proveedor_habitual: 'PROV-PAR-001',
      plazo_importacion_dias: 30,
      ctx: 'Ambos', activo: true,
    },
    {
      codigo: 'REP-3310-PER', cod: 'REP-3310-PER',
      descripcion: 'Culata de percusión SANDVIK', desc: 'Culata de percusión SANDVIK',
      marca: 'SANDVIK',
      modelos_compatibles: ['DD311'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Percusión',
      usd: 1450, precio_base: 1450,
      stock_actual: 0, stock: 0,
      stock_minimo: 1, min: 1,
      stock_reservado: 0,
      costo_aterrizado: 966,
      margen_estandar_pct: 50,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: null,
      es_importado: true,
      proveedor_habitual: 'PROV-SAN-001',
      plazo_importacion_dias: 60,
      ctx: 'Mina', activo: true,
    },
    {
      codigo: 'CAT-8T0814',
      descripcion: 'Filtro hidráulico R1600G',
      marca: 'Caterpillar',
      modelos_compatibles: ['R1600G', 'R1600H'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Filtros',
      usd: 180, precio_base: 180,
      stock_actual: 12, stock: 12,
      stock_minimo: 4, min: 4,
      stock_reservado: 6,
      costo_aterrizado: 120,
      margen_estandar_pct: 50,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'A-03-12',
      es_importado: true,
      proveedor_habitual: 'PROV-CAT-001',
      plazo_importacion_dias: 45,
      ctx: 'Ambos', activo: true,
    },
    {
      codigo: 'CAT-1R0741',
      descripcion: 'Filtro de aceite motor R1300G',
      marca: 'Caterpillar',
      modelos_compatibles: ['R1300G'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Filtros',
      usd: 95, precio_base: 95,
      stock_actual: 0, stock: 0,
      stock_minimo: 6, min: 6,
      stock_reservado: 0,
      costo_aterrizado: 63,
      margen_estandar_pct: 51,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: null,
      es_importado: true,
      proveedor_habitual: 'PROV-CAT-001',
      plazo_importacion_dias: 45,
      ctx: 'Ambos', activo: true,
    },
    {
      codigo: 'CAT-5P0960',
      descripcion: 'Sello de vástago cilindro dirección',
      marca: 'Caterpillar',
      modelos_compatibles: ['R1300G', 'R1600G'],
      unidad: 'Unidad', um: 'Unidad',
      cat: 'Hidráulico',
      usd: 48, precio_base: 48,
      stock_actual: 6, stock: 6,
      stock_minimo: 4, min: 4,
      stock_reservado: 0,
      costo_aterrizado: 32,
      margen_estandar_pct: 50,
      almacen: 'ALM-PRINCIPAL',
      ubicacion_fisica: 'B-04-07',
      es_importado: true,
      proveedor_habitual: 'PROV-CAT-001',
      plazo_importacion_dias: 45,
      ctx: 'Ambos', activo: true,
    },
  ],
};
